x-runtime-base: &runtime-base
  build:
    context: .
    dockerfile: "docker/Dockerfile.base"
    args:
      ROS_DISTRO: humble
    target: runtime
  image: horiokart_runtime
  tty: true
  network_mode: "host"
  privileged: true
  env_file:
    - .env
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority/:/root/.Xauthority
    - ./:/app/
    - /dev:/dev
    - ${HOME}/ros2_data:/root/ros2_data

x-develop-base: &develop-base
  build:
    context: .
    dockerfile: "docker/Dockerfile.base"
    args:
      ROS_DISTRO: humble
    target: develop
  image: horiokart_develop
  tty: true
  network_mode: "host"
  privileged: true
  env_file:
    - .env
  environment:
    - DISPLAY=${DISPLAY}
    - PYTHONUNBUFFERED=1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority/:/root/.Xauthority
    - ./:/app/
    - /dev:/dev
    - ${HOME}/ros2_data:/root/ros2_data

x-simulation-base: &simulation-base
  build:
    context: .
    dockerfile: "docker/Dockerfile.base"
    args:
      ROS_DISTRO: humble
    target: simulation
  image: horiokart_simulation
  tty: true
  network_mode: "host"
  privileged: true
  env_file:
    - .env
  environment:
    - DISPLAY=${DISPLAY}
    - PYTHONUNBUFFERED=1
    - SIMULATION=true
    - IGN_GAZEBO_RESOURCE_PATH=/root/.ignition/fuel
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority/:/root/.Xauthority
    - ./:/app/
    - /dev:/dev
    - ${HOME}/ros2_data:/root/ros2_data
    - ${HOME}/.ignition:/root/.ignition

services:
  slam:
    <<: *runtime-base
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONUNBUFFERED=1
      - USE_RVIZ=false
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 launch horiokart_bringup bringup_slam_toolbox.launch.py
      "

  navigation:
    <<: *runtime-base
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONUNBUFFERED=1
      - USE_RVIZ=false
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 launch horiokart_bringup bringup_navigation.launch.py
      "

  rosbag-replay:
    <<: *runtime-base
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONUNBUFFERED=1
      - SIMULATION=true
      - USE_RVIZ=false
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 launch horiokart_navigation bag_play.launch.py
      "

  gazebo-simulation:
    <<: *simulation-base
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        ros2 launch horiokart_simulation bringup.launch.py
      "

  develop:
    <<: *develop-base
    command: "/app/docker/docker-entrypoint.sh"

  rviz2-slam:
    <<: *develop-base
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        rviz2 --display-config /app/horiokart_slam/rviz/rviz.rviz
      "

  rviz2-navigation:
    <<: *develop-base
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        rviz2 --display-config /app/horiokart_navigation/rviz/rviz.rviz
      "

  rviz:
    <<: *develop-base
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONUNBUFFERED=1
      - RVIZ_CONFIG=${RVIZ_CONFIG:-}
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        rviz2 $${RVIZ_CONFIG:+--display-config $$RVIZ_CONFIG}
      "
