import enum


class SequencerState(enum.Enum):
    IDLE = "IDLE"
    COUNTDOWN = "COUNTDOWN"
    NAVIGATING = "NAVIGATING"
    EXECUTING_ACTIONS = "EXECUTING_ACTIONS"
    WAITING_TRIGGER = "WAITING_TRIGGER"
    SUSPENDED = "SUSPENDED"
    SUSPENDED_UNRESPONSIVE = "SUSPENDED_UNRESPONSIVE"
    GOAL_REACHED = "GOAL_REACHED"
    ERROR = "ERROR"
