slam_gnss_2d_offline_node:
  ros__parameters:
    bag_path: ""
    offline_step_hz: 30.0 # 可視化速度 [Hz]。0 以下で最大速度

    scan_topic: /scan_top_lidar
    odom_topic: /odom

    map_resolution: 0.05
    map_expansion_margin: 100.0
    min_translation: 0.3
    min_rotation: 0.1
    map_publish_hz: 1.0

    pose_graph_builder: loop_closure # "odom_only" | "scan_matching" | "loop_closure"
    scan_matcher_type: ndt # "icp" | "ndt"
    scan_reference: scan_to_local_map # "scan_to_scan" | "scan_to_local_map"

    icp_max_iterations: 30
    icp_tolerance: 0.0001
    icp_max_correspondence_dist: 1.0

    ndt_cell_size: 1.0

    local_map_window: 20
    local_map_radius: 20.0

    matcher_max_failure_streak: 5

    loop_closure_search_radius: 2.0
    loop_closure_min_node_gap: 50
    loop_closure_max_failure_streak: 3
    optimize_every_n_loops: 1
